triaged:
  - changed-files:
      - any-glob-to-any-file: "**/*"

feat:
  - head-branch:
      - ^feat*

enhancement:
  - changed-files:
      - any-glob-to-any-file:
          - confluent_kafka-stubs/*
  - head-branch:
      - ^refactor
      - ^enh*

confluent-kafka-v2.3:
  - head-branch:
      - "^feature/confluent-kafka-v2.3*"
      - "^feat/confluent-kafka-v2.3*"
      - "^refactor/confluent-kafka-v2.3*"
      - "^enhancement/confluent-kafka-v2.3*"
      - "^enh/confluent-kafka-v2.3*"
      - "^fix/confluent-kafka-v2.3*"
      - "^hotfix/confluent-kafka-v2.3*"

confluent-kafka-v2.4:
  - head-branch:
      - "^feature/confluent-kafka-v2.4*"
      - "^feat/confluent-kafka-v2.4*"
      - "^refactor/confluent-kafka-v2.4*"
      - "^enhancement/confluent-kafka-v2.4*"
      - "^enh/confluent-kafka-v2.4*"
      - "^fix/confluent-kafka-v2.4*"
      - "^hotfix/confluent-kafka-v2.4*"

confluent-kafka-v2.5:
  - head-branch:
      - "^feature/confluent-kafka-v2.5*"
      - "^feat/confluent-kafka-v2.5*"
      - "^refactor/confluent-kafka-v2.5*"
      - "^enhancement/confluent-kafka-v2.5*"
      - "^enh/confluent-kafka-v2.5*"
      - "^fix/confluent-kafka-v2.5*"
      - "^hotfix/confluent-kafka-v2.5*"

confluent-kafka-v2.6:
  - head-branch:
      - "^feature/confluent-kafka-v2.6*"
      - "^feat/confluent-kafka-v2.6*"
      - "^refactor/confluent-kafka-v2.6*"
      - "^enhancement/confluent-kafka-v2.6*"
      - "^enh/confluent-kafka-v2.6*"
      - "^fix/confluent-kafka-v2.6*"
      - "^hotfix/confluent-kafka-v2.6*"

workflow:
  - changed-files:
      - any-glob-to-any-file:
          - .github/*
          - .plugins/*
  - head-branch:
      - ^workflow
      - ^ci

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - README.md
          - docs/*
