"""
types-confluent-kafka: A package providing type hints for the confluent-kafka Python package.
This package is licensed under the Apache 2.0 License.
"""

from __future__ import annotations

# standard library
import asyncio
from typing import Any, Dict, List, Optional

from ...cimpl import Message
from ._kafka_batch_executor import ProducerBatchExecutor
from ._message_batch import MessageBatch

class ProducerBatchManager:
    def __init__(self, kafka_executor: ProducerBatchExecutor) -> None: ...
    def add_message(self, msg_data: Dict[str, Any], future: asyncio.Future[Message]) -> None: ...
    def get_buffer_size(self) -> int: ...
    def is_buffer_empty(self) -> bool: ...
    def clear_buffer(self) -> None: ...
    def cancel_pending_futures(self) -> None: ...
    def create_batches(self, target_topic: Optional[str] = None) -> List[MessageBatch]: ...
    async def flush_buffer(self, target_topic: Optional[str] = None) -> None: ...
