---
blank_issues_enabled: false
contact_links:
  - name: 🤔 Ask a Question
    url: "https://github.com/benbenbang/types-confluent-kafka/discussions/new/choose"
    about: "Ask a question about how to use types-confluent-kafka or any other topics that don't fit into issues."
