"""
types-confluent-kafka: A package providing type hints for the confluent-kafka Python package.
This package is licensed under the Apache 2.0 License.
"""

from __future__ import annotations

# standard library
import concurrent.futures
from typing import Any, Callable

from ..admin._metadata import ClusterMetadata
from ..cimpl import Message, TopicPartition

class AIOConsumer:
    def __init__(
        self,
        consumer_conf: dict[str, Any],
        max_workers: int = 2,
        executor: concurrent.futures.Executor | None = None,
    ) -> None: ...
    async def __aenter__(self) -> AIOConsumer: ...
    async def __aexit__(self, *_: Any) -> None: ...
    async def poll(self, timeout: float | int | None = None) -> Message | None: ...
    async def consume(self, num_messages: int = 1, timeout: float | int = -1) -> list[Message]: ...
    async def subscribe(
        self,
        topics: list[str],
        on_assign: Callable[[AIOConsumer, list[TopicPartition]], Any] | None = None,
        on_revoke: Callable[[AIOConsumer, list[TopicPartition]], Any] | None = None,
        on_lost: Callable[[AIOConsumer, list[TopicPartition]], Any] | None = None,
    ) -> None: ...
    async def unsubscribe(self) -> None: ...
    async def commit(
        self,
        message: Message | None = None,
        offsets: list[TopicPartition] | None = None,
        asynchronous: bool = True,
    ) -> list[TopicPartition] | None: ...
    async def close(self) -> None: ...
    async def seek(self, partition: TopicPartition) -> None: ...
    async def pause(self, partitions: list[TopicPartition]) -> None: ...
    async def resume(self, partitions: list[TopicPartition]) -> None: ...
    async def store_offsets(
        self,
        message: Message | None = None,
        offsets: list[TopicPartition] | None = None,
    ) -> None: ...
    async def committed(
        self,
        partitions: list[TopicPartition],
        timeout: float | int | None = None,
    ) -> list[TopicPartition]: ...
    async def assign(self, partitions: list[TopicPartition]) -> None: ...
    async def unassign(self) -> None: ...
    async def incremental_assign(self, partitions: list[TopicPartition]) -> None: ...
    async def incremental_unassign(self, partitions: list[TopicPartition]) -> None: ...
    async def assignment(self) -> list[TopicPartition]: ...
    async def position(self, partitions: list[TopicPartition]) -> list[TopicPartition]: ...
    async def consumer_group_metadata(self) -> bytes: ...
    async def set_sasl_credentials(self, username: str, password: str) -> None: ...
    async def list_topics(self, topic: str | None = None, timeout: float | int = -1) -> ClusterMetadata: ...
    async def get_watermark_offsets(
        self,
        partition: TopicPartition,
        timeout: float | int | None = None,
        cached: bool = False,
    ) -> tuple[int, int]: ...
    async def offsets_for_times(
        self,
        partitions: list[TopicPartition],
        timeout: float | int | None = None,
    ) -> list[TopicPartition]: ...
