name: publish-pypi

on:
  push:
    tags:
      - "^[0-9]+.[0-9]+.[0-9]+$"

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: prepare pipx, poetry and dependencies
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath
          pipx install poetry=="${poetry_version}"
          poetry install
          poetry show
      - name: publish pypi
        run: |
          pipx run poetry version ${{ github.ref_name }}
          pipx run poetry build
          pipx run poetry run twine upload --repository pypi dist/*
