name: publish

on:
  release:
    types:
      - published

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: install dependencies
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath
          pipx install uv=="${uv_version}"
          pipx run uv sync --all-groups
          pip freeze
        env:
          uv_version: "0.7.19"

      - name: extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: build with uv
        run: |
          echo "build with release version: ${TAG_NAME}"
          pipx run uv version ${TAG_NAME} || echo "toml is already up to date."
          pipx run uv build

      - name: publish to pypi
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          pipx run uv publish -u ${PYPI_USERNAME} -p $PYPI_TOKEN

      - name: update title && upload distribution to GitHub Release
        run: |
          gh release edit "${TAG_NAME}" --title "Types Confluent Kafka ${TAG_NAME}"
          gh release upload ${TAG_NAME} dist/*
        env:
          GH_TOKEN: ${{ secrets.PTAH_CI_TOKEN }}
