name: pull-request-target-workflows

on:
  pull_request_target:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}-labeler
  cancel-in-progress: true

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    continue-on-error: true
    permissions:
      pull-requests: write
      contents: read
    steps:
      - uses: actions/labeler@v5
        continue-on-error: true
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml
