name: pr-title-check

on:
  pull_request:
    branches:
      - main

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Prepare testing environment
        run: |
          git config --global user.email "pr-title-check@github.com"
          git config --global user.name "pr-title-validator"
          pip install pre-commit
          pre-commit install && pre-commit install --hook commit-msg
      - name: Check title with dummy commit message
        run: |
          echo "checking PR title: '${{ github.event.pull_request.title }}'"
          git commit --allow-empty -m "${{ github.event.pull_request.title }}"
