name: release

on:
  push:
    tags:
      - \d+\.\d+\.\d+
    branches:
      - confluent-kafka-v*

permissions:
  contents: write
  issues: write
  pull-requests: write
  id-token: write
  packages: read

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 50

      - name: extract tag name
        run: |
          export TAG_NAME=${GITHUB_REF#refs/tags/}
          echo "Extracted tag name: $TAG_NAME"
          echo "TAG_NAME=${TAG_NAME} >> $GITHUB_ENV"

      - name: semantic release
        run: |
          gh release create --repo ${{ github.repository }} \
                            --title "Types Confluent Kafka ${TAG_NAME}" \
                            --target ${GITHUB_HEAD_REF} \
                            --generate-notes \
                            --latest \
                            $TAG_NAME
        env:
          GH_TOKEN: ${{ secrets.PTAH_CI_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GH_GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: ${{ secrets.GH_GIT_AUTHOR_NAME }}
          GIT_COMMITTER_EMAIL: ${{ secrets.GH_GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: ${{ secrets.GH_GIT_COMMITTER_NAME }}

  publish:
    name: publish
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}/pre-commit:py3.12
      options: -w ${{ github.workspace }}
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    needs: release
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: show dependencies
        run: |
          pip list
      - name: extract tag name
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: build with uv
        run: |
          echo "build with release version: ${TAG_NAME}"
          uv version ${TAG_NAME} || echo "toml is already up to date."
          uv build
      - name: publish to pypi
        env:
          PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          uv publish -u ${PYPI_USERNAME} -p $PYPI_TOKEN
      - name: update title  && upload distribution to GitHub Release
        run: |
          gh release upload ${TAG_NAME} dist/*
        env:
          GH_TOKEN: ${{ secrets.PTAH_CI_TOKEN }}
